name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js you need

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint step
      - name: Run Lint
        run: npm run lint

      # Run Tests
      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js you need

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          # Artifact name
          name: Dist
          path: dist/
        
          
       
